// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class BlockwiseQuantization {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):BlockwiseQuantization {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBlockwiseQuantization(bb:flatbuffers.ByteBuffer, obj?:BlockwiseQuantization):BlockwiseQuantization {
  return (obj || new BlockwiseQuantization()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBlockwiseQuantization(bb:flatbuffers.ByteBuffer, obj?:BlockwiseQuantization):BlockwiseQuantization {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new BlockwiseQuantization()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

scales():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

zeroPoints():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

blockSize():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startBlockwiseQuantization(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addScales(builder:flatbuffers.Builder, scales:number) {
  builder.addFieldInt32(0, scales, 0);
}

static addZeroPoints(builder:flatbuffers.Builder, zeroPoints:number) {
  builder.addFieldInt32(1, zeroPoints, 0);
}

static addBlockSize(builder:flatbuffers.Builder, blockSize:number) {
  builder.addFieldInt32(2, blockSize, 0);
}

static endBlockwiseQuantization(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createBlockwiseQuantization(builder:flatbuffers.Builder, scales:number, zeroPoints:number, blockSize:number):flatbuffers.Offset {
  BlockwiseQuantization.startBlockwiseQuantization(builder);
  BlockwiseQuantization.addScales(builder, scales);
  BlockwiseQuantization.addZeroPoints(builder, zeroPoints);
  BlockwiseQuantization.addBlockSize(builder, blockSize);
  return BlockwiseQuantization.endBlockwiseQuantization(builder);
}
}
