// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { DilateOptions } from '../tflite/dilate-options';
import { ReduceWindowOptions } from '../tflite/reduce-window-options';
import { StableHLOCompositeOptions } from '../tflite/stable-hlocomposite-options';
import { StablehloBroadcastInDimOptions } from '../tflite/stablehlo-broadcast-in-dim-options';
import { StablehloCaseOptions } from '../tflite/stablehlo-case-options';
import { StablehloCompareOptions } from '../tflite/stablehlo-compare-options';
import { StablehloConcatenateOptions } from '../tflite/stablehlo-concatenate-options';
import { StablehloConvolutionOptions } from '../tflite/stablehlo-convolution-options';
import { StablehloCustomCallOptions } from '../tflite/stablehlo-custom-call-options';
import { StablehloDotGeneralOptions } from '../tflite/stablehlo-dot-general-options';
import { StablehloDynamicSliceOptions } from '../tflite/stablehlo-dynamic-slice-options';
import { StablehloGatherOptions } from '../tflite/stablehlo-gather-options';
import { StablehloIotaOptions } from '../tflite/stablehlo-iota-options';
import { StablehloPadOptions } from '../tflite/stablehlo-pad-options';
import { StablehloReduceOptions } from '../tflite/stablehlo-reduce-options';
import { StablehloReduceWindowOptions } from '../tflite/stablehlo-reduce-window-options';
import { StablehloRngBitGeneratorOptions } from '../tflite/stablehlo-rng-bit-generator-options';
import { StablehloScatterOptions } from '../tflite/stablehlo-scatter-options';
import { StablehloShiftLeftOptions } from '../tflite/stablehlo-shift-left-options';
import { StablehloSliceOptions } from '../tflite/stablehlo-slice-options';
import { StablehloSortOptions } from '../tflite/stablehlo-sort-options';
import { StablehloTransposeOptions } from '../tflite/stablehlo-transpose-options';
import { StablehloWhileOptions } from '../tflite/stablehlo-while-options';


export enum BuiltinOptions2 {
  NONE = 0,
  StablehloConcatenateOptions = 1,
  StablehloBroadcastInDimOptions = 2,
  StablehloSliceOptions = 3,
  StablehloConvolutionOptions = 4,
  StablehloCustomCallOptions = 5,
  StablehloReduceOptions = 6,
  StablehloScatterOptions = 7,
  StablehloCompareOptions = 8,
  StablehloDynamicSliceOptions = 9,
  StablehloPadOptions = 10,
  StablehloIotaOptions = 11,
  StablehloDotGeneralOptions = 12,
  StablehloReduceWindowOptions = 13,
  StablehloSortOptions = 14,
  StablehloWhileOptions = 15,
  StablehloGatherOptions = 16,
  StablehloTransposeOptions = 17,
  DilateOptions = 18,
  StablehloRngBitGeneratorOptions = 19,
  ReduceWindowOptions = 20,
  StableHLOCompositeOptions = 21,
  StablehloShiftLeftOptions = 22,
  StablehloCaseOptions = 23
}

export function unionToBuiltinOptions2(
  type: BuiltinOptions2,
  accessor: (obj:DilateOptions|ReduceWindowOptions|StableHLOCompositeOptions|StablehloBroadcastInDimOptions|StablehloCaseOptions|StablehloCompareOptions|StablehloConcatenateOptions|StablehloConvolutionOptions|StablehloCustomCallOptions|StablehloDotGeneralOptions|StablehloDynamicSliceOptions|StablehloGatherOptions|StablehloIotaOptions|StablehloPadOptions|StablehloReduceOptions|StablehloReduceWindowOptions|StablehloRngBitGeneratorOptions|StablehloScatterOptions|StablehloShiftLeftOptions|StablehloSliceOptions|StablehloSortOptions|StablehloTransposeOptions|StablehloWhileOptions) => DilateOptions|ReduceWindowOptions|StableHLOCompositeOptions|StablehloBroadcastInDimOptions|StablehloCaseOptions|StablehloCompareOptions|StablehloConcatenateOptions|StablehloConvolutionOptions|StablehloCustomCallOptions|StablehloDotGeneralOptions|StablehloDynamicSliceOptions|StablehloGatherOptions|StablehloIotaOptions|StablehloPadOptions|StablehloReduceOptions|StablehloReduceWindowOptions|StablehloRngBitGeneratorOptions|StablehloScatterOptions|StablehloShiftLeftOptions|StablehloSliceOptions|StablehloSortOptions|StablehloTransposeOptions|StablehloWhileOptions|null
): DilateOptions|ReduceWindowOptions|StableHLOCompositeOptions|StablehloBroadcastInDimOptions|StablehloCaseOptions|StablehloCompareOptions|StablehloConcatenateOptions|StablehloConvolutionOptions|StablehloCustomCallOptions|StablehloDotGeneralOptions|StablehloDynamicSliceOptions|StablehloGatherOptions|StablehloIotaOptions|StablehloPadOptions|StablehloReduceOptions|StablehloReduceWindowOptions|StablehloRngBitGeneratorOptions|StablehloScatterOptions|StablehloShiftLeftOptions|StablehloSliceOptions|StablehloSortOptions|StablehloTransposeOptions|StablehloWhileOptions|null {
  switch(BuiltinOptions2[type]) {
    case 'NONE': return null; 
    case 'StablehloConcatenateOptions': return accessor(new StablehloConcatenateOptions())! as StablehloConcatenateOptions;
    case 'StablehloBroadcastInDimOptions': return accessor(new StablehloBroadcastInDimOptions())! as StablehloBroadcastInDimOptions;
    case 'StablehloSliceOptions': return accessor(new StablehloSliceOptions())! as StablehloSliceOptions;
    case 'StablehloConvolutionOptions': return accessor(new StablehloConvolutionOptions())! as StablehloConvolutionOptions;
    case 'StablehloCustomCallOptions': return accessor(new StablehloCustomCallOptions())! as StablehloCustomCallOptions;
    case 'StablehloReduceOptions': return accessor(new StablehloReduceOptions())! as StablehloReduceOptions;
    case 'StablehloScatterOptions': return accessor(new StablehloScatterOptions())! as StablehloScatterOptions;
    case 'StablehloCompareOptions': return accessor(new StablehloCompareOptions())! as StablehloCompareOptions;
    case 'StablehloDynamicSliceOptions': return accessor(new StablehloDynamicSliceOptions())! as StablehloDynamicSliceOptions;
    case 'StablehloPadOptions': return accessor(new StablehloPadOptions())! as StablehloPadOptions;
    case 'StablehloIotaOptions': return accessor(new StablehloIotaOptions())! as StablehloIotaOptions;
    case 'StablehloDotGeneralOptions': return accessor(new StablehloDotGeneralOptions())! as StablehloDotGeneralOptions;
    case 'StablehloReduceWindowOptions': return accessor(new StablehloReduceWindowOptions())! as StablehloReduceWindowOptions;
    case 'StablehloSortOptions': return accessor(new StablehloSortOptions())! as StablehloSortOptions;
    case 'StablehloWhileOptions': return accessor(new StablehloWhileOptions())! as StablehloWhileOptions;
    case 'StablehloGatherOptions': return accessor(new StablehloGatherOptions())! as StablehloGatherOptions;
    case 'StablehloTransposeOptions': return accessor(new StablehloTransposeOptions())! as StablehloTransposeOptions;
    case 'DilateOptions': return accessor(new DilateOptions())! as DilateOptions;
    case 'StablehloRngBitGeneratorOptions': return accessor(new StablehloRngBitGeneratorOptions())! as StablehloRngBitGeneratorOptions;
    case 'ReduceWindowOptions': return accessor(new ReduceWindowOptions())! as ReduceWindowOptions;
    case 'StableHLOCompositeOptions': return accessor(new StableHLOCompositeOptions())! as StableHLOCompositeOptions;
    case 'StablehloShiftLeftOptions': return accessor(new StablehloShiftLeftOptions())! as StablehloShiftLeftOptions;
    case 'StablehloCaseOptions': return accessor(new StablehloCaseOptions())! as StablehloCaseOptions;
    default: return null;
  }
}

export function unionListToBuiltinOptions2(
  type: BuiltinOptions2, 
  accessor: (index: number, obj:DilateOptions|ReduceWindowOptions|StableHLOCompositeOptions|StablehloBroadcastInDimOptions|StablehloCaseOptions|StablehloCompareOptions|StablehloConcatenateOptions|StablehloConvolutionOptions|StablehloCustomCallOptions|StablehloDotGeneralOptions|StablehloDynamicSliceOptions|StablehloGatherOptions|StablehloIotaOptions|StablehloPadOptions|StablehloReduceOptions|StablehloReduceWindowOptions|StablehloRngBitGeneratorOptions|StablehloScatterOptions|StablehloShiftLeftOptions|StablehloSliceOptions|StablehloSortOptions|StablehloTransposeOptions|StablehloWhileOptions) => DilateOptions|ReduceWindowOptions|StableHLOCompositeOptions|StablehloBroadcastInDimOptions|StablehloCaseOptions|StablehloCompareOptions|StablehloConcatenateOptions|StablehloConvolutionOptions|StablehloCustomCallOptions|StablehloDotGeneralOptions|StablehloDynamicSliceOptions|StablehloGatherOptions|StablehloIotaOptions|StablehloPadOptions|StablehloReduceOptions|StablehloReduceWindowOptions|StablehloRngBitGeneratorOptions|StablehloScatterOptions|StablehloShiftLeftOptions|StablehloSliceOptions|StablehloSortOptions|StablehloTransposeOptions|StablehloWhileOptions|null, 
  index: number
): DilateOptions|ReduceWindowOptions|StableHLOCompositeOptions|StablehloBroadcastInDimOptions|StablehloCaseOptions|StablehloCompareOptions|StablehloConcatenateOptions|StablehloConvolutionOptions|StablehloCustomCallOptions|StablehloDotGeneralOptions|StablehloDynamicSliceOptions|StablehloGatherOptions|StablehloIotaOptions|StablehloPadOptions|StablehloReduceOptions|StablehloReduceWindowOptions|StablehloRngBitGeneratorOptions|StablehloScatterOptions|StablehloShiftLeftOptions|StablehloSliceOptions|StablehloSortOptions|StablehloTransposeOptions|StablehloWhileOptions|null {
  switch(BuiltinOptions2[type]) {
    case 'NONE': return null; 
    case 'StablehloConcatenateOptions': return accessor(index, new StablehloConcatenateOptions())! as StablehloConcatenateOptions;
    case 'StablehloBroadcastInDimOptions': return accessor(index, new StablehloBroadcastInDimOptions())! as StablehloBroadcastInDimOptions;
    case 'StablehloSliceOptions': return accessor(index, new StablehloSliceOptions())! as StablehloSliceOptions;
    case 'StablehloConvolutionOptions': return accessor(index, new StablehloConvolutionOptions())! as StablehloConvolutionOptions;
    case 'StablehloCustomCallOptions': return accessor(index, new StablehloCustomCallOptions())! as StablehloCustomCallOptions;
    case 'StablehloReduceOptions': return accessor(index, new StablehloReduceOptions())! as StablehloReduceOptions;
    case 'StablehloScatterOptions': return accessor(index, new StablehloScatterOptions())! as StablehloScatterOptions;
    case 'StablehloCompareOptions': return accessor(index, new StablehloCompareOptions())! as StablehloCompareOptions;
    case 'StablehloDynamicSliceOptions': return accessor(index, new StablehloDynamicSliceOptions())! as StablehloDynamicSliceOptions;
    case 'StablehloPadOptions': return accessor(index, new StablehloPadOptions())! as StablehloPadOptions;
    case 'StablehloIotaOptions': return accessor(index, new StablehloIotaOptions())! as StablehloIotaOptions;
    case 'StablehloDotGeneralOptions': return accessor(index, new StablehloDotGeneralOptions())! as StablehloDotGeneralOptions;
    case 'StablehloReduceWindowOptions': return accessor(index, new StablehloReduceWindowOptions())! as StablehloReduceWindowOptions;
    case 'StablehloSortOptions': return accessor(index, new StablehloSortOptions())! as StablehloSortOptions;
    case 'StablehloWhileOptions': return accessor(index, new StablehloWhileOptions())! as StablehloWhileOptions;
    case 'StablehloGatherOptions': return accessor(index, new StablehloGatherOptions())! as StablehloGatherOptions;
    case 'StablehloTransposeOptions': return accessor(index, new StablehloTransposeOptions())! as StablehloTransposeOptions;
    case 'DilateOptions': return accessor(index, new DilateOptions())! as DilateOptions;
    case 'StablehloRngBitGeneratorOptions': return accessor(index, new StablehloRngBitGeneratorOptions())! as StablehloRngBitGeneratorOptions;
    case 'ReduceWindowOptions': return accessor(index, new ReduceWindowOptions())! as ReduceWindowOptions;
    case 'StableHLOCompositeOptions': return accessor(index, new StableHLOCompositeOptions())! as StableHLOCompositeOptions;
    case 'StablehloShiftLeftOptions': return accessor(index, new StablehloShiftLeftOptions())! as StablehloShiftLeftOptions;
    case 'StablehloCaseOptions': return accessor(index, new StablehloCaseOptions())! as StablehloCaseOptions;
    default: return null;
  }
}
