// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class DilateOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DilateOptions {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDilateOptions(bb:flatbuffers.ByteBuffer, obj?:DilateOptions):DilateOptions {
  return (obj || new DilateOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDilateOptions(bb:flatbuffers.ByteBuffer, obj?:DilateOptions):DilateOptions {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DilateOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startDilateOptions(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endDilateOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDilateOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  DilateOptions.startDilateOptions(builder);
  return DilateOptions.endDilateOptions(builder);
}
}
