// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class DynamicUpdateSliceOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DynamicUpdateSliceOptions {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDynamicUpdateSliceOptions(bb:flatbuffers.ByteBuffer, obj?:DynamicUpdateSliceOptions):DynamicUpdateSliceOptions {
  return (obj || new DynamicUpdateSliceOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDynamicUpdateSliceOptions(bb:flatbuffers.ByteBuffer, obj?:DynamicUpdateSliceOptions):DynamicUpdateSliceOptions {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DynamicUpdateSliceOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startDynamicUpdateSliceOptions(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endDynamicUpdateSliceOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDynamicUpdateSliceOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  DynamicUpdateSliceOptions.startDynamicUpdateSliceOptions(builder);
  return DynamicUpdateSliceOptions.endDynamicUpdateSliceOptions(builder);
}
}
