// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ExternalBuffer {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ExternalBuffer {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsExternalBuffer(bb:flatbuffers.ByteBuffer, obj?:ExternalBuffer):ExternalBuffer {
  return (obj || new ExternalBuffer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsExternalBuffer(bb:flatbuffers.ByteBuffer, obj?:ExternalBuffer):ExternalBuffer {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ExternalBuffer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

group():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

offset():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

length():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

packing():string|null
packing(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
packing(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startExternalBuffer(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static addGroup(builder:flatbuffers.Builder, group:number) {
  builder.addFieldInt32(1, group, 0);
}

static addOffset(builder:flatbuffers.Builder, offset:bigint) {
  builder.addFieldInt64(2, offset, BigInt('0'));
}

static addLength(builder:flatbuffers.Builder, length:bigint) {
  builder.addFieldInt64(3, length, BigInt('0'));
}

static addPacking(builder:flatbuffers.Builder, packingOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, packingOffset, 0);
}

static endExternalBuffer(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createExternalBuffer(builder:flatbuffers.Builder, id:number, group:number, offset:bigint, length:bigint, packingOffset:flatbuffers.Offset):flatbuffers.Offset {
  ExternalBuffer.startExternalBuffer(builder);
  ExternalBuffer.addId(builder, id);
  ExternalBuffer.addGroup(builder, group);
  ExternalBuffer.addOffset(builder, offset);
  ExternalBuffer.addLength(builder, length);
  ExternalBuffer.addPacking(builder, packingOffset);
  return ExternalBuffer.endExternalBuffer(builder);
}
}
