// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ActivationFunctionType } from '../tflite/activation-function-type';
import { FullyConnectedOptionsWeightsFormat } from '../tflite/fully-connected-options-weights-format';
import { TensorType } from '../tflite/tensor-type';


export class FullyConnectedOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FullyConnectedOptions {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFullyConnectedOptions(bb:flatbuffers.ByteBuffer, obj?:FullyConnectedOptions):FullyConnectedOptions {
  return (obj || new FullyConnectedOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFullyConnectedOptions(bb:flatbuffers.ByteBuffer, obj?:FullyConnectedOptions):FullyConnectedOptions {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FullyConnectedOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

fusedActivationFunction():ActivationFunctionType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ActivationFunctionType.NONE;
}

weightsFormat():FullyConnectedOptionsWeightsFormat {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : FullyConnectedOptionsWeightsFormat.DEFAULT;
}

keepNumDims():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

asymmetricQuantizeInputs():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

quantizedBiasType():TensorType {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : TensorType.FLOAT32;
}

static startFullyConnectedOptions(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addFusedActivationFunction(builder:flatbuffers.Builder, fusedActivationFunction:ActivationFunctionType) {
  builder.addFieldInt8(0, fusedActivationFunction, ActivationFunctionType.NONE);
}

static addWeightsFormat(builder:flatbuffers.Builder, weightsFormat:FullyConnectedOptionsWeightsFormat) {
  builder.addFieldInt8(1, weightsFormat, FullyConnectedOptionsWeightsFormat.DEFAULT);
}

static addKeepNumDims(builder:flatbuffers.Builder, keepNumDims:boolean) {
  builder.addFieldInt8(2, +keepNumDims, +false);
}

static addAsymmetricQuantizeInputs(builder:flatbuffers.Builder, asymmetricQuantizeInputs:boolean) {
  builder.addFieldInt8(3, +asymmetricQuantizeInputs, +false);
}

static addQuantizedBiasType(builder:flatbuffers.Builder, quantizedBiasType:TensorType) {
  builder.addFieldInt8(4, quantizedBiasType, TensorType.FLOAT32);
}

static endFullyConnectedOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFullyConnectedOptions(builder:flatbuffers.Builder, fusedActivationFunction:ActivationFunctionType, weightsFormat:FullyConnectedOptionsWeightsFormat, keepNumDims:boolean, asymmetricQuantizeInputs:boolean, quantizedBiasType:TensorType):flatbuffers.Offset {
  FullyConnectedOptions.startFullyConnectedOptions(builder);
  FullyConnectedOptions.addFusedActivationFunction(builder, fusedActivationFunction);
  FullyConnectedOptions.addWeightsFormat(builder, weightsFormat);
  FullyConnectedOptions.addKeepNumDims(builder, keepNumDims);
  FullyConnectedOptions.addAsymmetricQuantizeInputs(builder, asymmetricQuantizeInputs);
  FullyConnectedOptions.addQuantizedBiasType(builder, quantizedBiasType);
  return FullyConnectedOptions.endFullyConnectedOptions(builder);
}
}
