// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum FullyConnectedOptionsWeightsFormat {
  DEFAULT = 0,
  SHUFFLED4x16INT8 = 1
}
