// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { BlockwiseQuantization } from '../tflite/blockwise-quantization';
import { CustomQuantization } from '../tflite/custom-quantization';


export enum QuantizationDetails {
  NONE = 0,
  CustomQuantization = 1,
  BlockwiseQuantization = 2
}

export function unionToQuantizationDetails(
  type: QuantizationDetails,
  accessor: (obj:BlockwiseQuantization|CustomQuantization) => BlockwiseQuantization|CustomQuantization|null
): BlockwiseQuantization|CustomQuantization|null {
  switch(QuantizationDetails[type]) {
    case 'NONE': return null; 
    case 'CustomQuantization': return accessor(new CustomQuantization())! as CustomQuantization;
    case 'BlockwiseQuantization': return accessor(new BlockwiseQuantization())! as BlockwiseQuantization;
    default: return null;
  }
}

export function unionListToQuantizationDetails(
  type: QuantizationDetails, 
  accessor: (index: number, obj:BlockwiseQuantization|CustomQuantization) => BlockwiseQuantization|CustomQuantization|null, 
  index: number
): BlockwiseQuantization|CustomQuantization|null {
  switch(QuantizationDetails[type]) {
    case 'NONE': return null; 
    case 'CustomQuantization': return accessor(index, new CustomQuantization())! as CustomQuantization;
    case 'BlockwiseQuantization': return accessor(index, new BlockwiseQuantization())! as BlockwiseQuantization;
    default: return null;
  }
}
