// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ReduceWindowFunction {
  UNSUPPORTED = 0,
  ADD = 1,
  MUL = 2,
  MINIMUM = 3,
  MAXIMUM = 4,
  ALL = 5,
  ANY = 6
}
