// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class RightShiftOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RightShiftOptions {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRightShiftOptions(bb:flatbuffers.ByteBuffer, obj?:RightShiftOptions):RightShiftOptions {
  return (obj || new RightShiftOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRightShiftOptions(bb:flatbuffers.ByteBuffer, obj?:RightShiftOptions):RightShiftOptions {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RightShiftOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startRightShiftOptions(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endRightShiftOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRightShiftOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  RightShiftOptions.startRightShiftOptions(builder);
  return RightShiftOptions.endRightShiftOptions(builder);
}
}
