// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum RngAlgorithm {
  DEFAULT = 0,
  PHILOX = 1,
  THREEFRY = 2
}
