// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class StablehloShiftLeftOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StablehloShiftLeftOptions {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStablehloShiftLeftOptions(bb:flatbuffers.ByteBuffer, obj?:StablehloShiftLeftOptions):StablehloShiftLeftOptions {
  return (obj || new StablehloShiftLeftOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStablehloShiftLeftOptions(bb:flatbuffers.ByteBuffer, obj?:StablehloShiftLeftOptions):StablehloShiftLeftOptions {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StablehloShiftLeftOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startStablehloShiftLeftOptions(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endStablehloShiftLeftOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStablehloShiftLeftOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  StablehloShiftLeftOptions.startStablehloShiftLeftOptions(builder);
  return StablehloShiftLeftOptions.endStablehloShiftLeftOptions(builder);
}
}
