// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class StablehloConcatenateOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StablehloConcatenateOptions {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStablehloConcatenateOptions(bb:flatbuffers.ByteBuffer, obj?:StablehloConcatenateOptions):StablehloConcatenateOptions {
  return (obj || new StablehloConcatenateOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStablehloConcatenateOptions(bb:flatbuffers.ByteBuffer, obj?:StablehloConcatenateOptions):StablehloConcatenateOptions {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StablehloConcatenateOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

dimension():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startStablehloConcatenateOptions(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addDimension(builder:flatbuffers.Builder, dimension:bigint) {
  builder.addFieldInt64(0, dimension, BigInt('0'));
}

static endStablehloConcatenateOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStablehloConcatenateOptions(builder:flatbuffers.Builder, dimension:bigint):flatbuffers.Offset {
  StablehloConcatenateOptions.startStablehloConcatenateOptions(builder);
  StablehloConcatenateOptions.addDimension(builder, dimension);
  return StablehloConcatenateOptions.endStablehloConcatenateOptions(builder);
}
}
