// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum StablehloPrecisionConfig {
  DEFAULT = 0,
  HIGH = 1,
  HIGHEST = 2
}
