// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum StablehloComparisonDirection {
  STABLEHLO_COMPARISON_DIRECTION_EQ = 0,
  STABLEHLO_COMPARISON_DIRECTION_NE = 1,
  STABLEHLO_COMPARISON_DIRECTION_GE = 2,
  STABLEHLO_COMPARISON_DIRECTION_GT = 3,
  STABLEHLO_COMPARISON_DIRECTION_LE = 4,
  STABLEHLO_COMPARISON_DIRECTION_LT = 5
}
