// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class StablehloIotaOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StablehloIotaOptions {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStablehloIotaOptions(bb:flatbuffers.ByteBuffer, obj?:StablehloIotaOptions):StablehloIotaOptions {
  return (obj || new StablehloIotaOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStablehloIotaOptions(bb:flatbuffers.ByteBuffer, obj?:StablehloIotaOptions):StablehloIotaOptions {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StablehloIotaOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

iotaDimension():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startStablehloIotaOptions(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addIotaDimension(builder:flatbuffers.Builder, iotaDimension:bigint) {
  builder.addFieldInt64(0, iotaDimension, BigInt('0'));
}

static endStablehloIotaOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStablehloIotaOptions(builder:flatbuffers.Builder, iotaDimension:bigint):flatbuffers.Offset {
  StablehloIotaOptions.startStablehloIotaOptions(builder);
  StablehloIotaOptions.addIotaDimension(builder, iotaDimension);
  return StablehloIotaOptions.endStablehloIotaOptions(builder);
}
}
