// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CustomOptionsFormat } from '../tflite/custom-options-format';


export class StableHLOCompositeOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StableHLOCompositeOptions {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStableHLOCompositeOptions(bb:flatbuffers.ByteBuffer, obj?:StableHLOCompositeOptions):StableHLOCompositeOptions {
  return (obj || new StableHLOCompositeOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStableHLOCompositeOptions(bb:flatbuffers.ByteBuffer, obj?:StableHLOCompositeOptions):StableHLOCompositeOptions {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StableHLOCompositeOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

decompositionSubgraphIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

compositeAttributes(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

compositeAttributesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

compositeAttributesArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

compositeAttributesFormat():CustomOptionsFormat {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : CustomOptionsFormat.FLEXBUFFERS;
}

version():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startStableHLOCompositeOptions(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addDecompositionSubgraphIndex(builder:flatbuffers.Builder, decompositionSubgraphIndex:number) {
  builder.addFieldInt32(1, decompositionSubgraphIndex, 0);
}

static addCompositeAttributes(builder:flatbuffers.Builder, compositeAttributesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, compositeAttributesOffset, 0);
}

static createCompositeAttributesVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startCompositeAttributesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addCompositeAttributesFormat(builder:flatbuffers.Builder, compositeAttributesFormat:CustomOptionsFormat) {
  builder.addFieldInt8(3, compositeAttributesFormat, CustomOptionsFormat.FLEXBUFFERS);
}

static addVersion(builder:flatbuffers.Builder, version:number) {
  builder.addFieldInt32(4, version, 0);
}

static endStableHLOCompositeOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStableHLOCompositeOptions(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, decompositionSubgraphIndex:number, compositeAttributesOffset:flatbuffers.Offset, compositeAttributesFormat:CustomOptionsFormat, version:number):flatbuffers.Offset {
  StableHLOCompositeOptions.startStableHLOCompositeOptions(builder);
  StableHLOCompositeOptions.addName(builder, nameOffset);
  StableHLOCompositeOptions.addDecompositionSubgraphIndex(builder, decompositionSubgraphIndex);
  StableHLOCompositeOptions.addCompositeAttributes(builder, compositeAttributesOffset);
  StableHLOCompositeOptions.addCompositeAttributesFormat(builder, compositeAttributesFormat);
  StableHLOCompositeOptions.addVersion(builder, version);
  return StableHLOCompositeOptions.endStableHLOCompositeOptions(builder);
}
}
