// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class StablehloSortOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StablehloSortOptions {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStablehloSortOptions(bb:flatbuffers.ByteBuffer, obj?:StablehloSortOptions):StablehloSortOptions {
  return (obj || new StablehloSortOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStablehloSortOptions(bb:flatbuffers.ByteBuffer, obj?:StablehloSortOptions):StablehloSortOptions {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StablehloSortOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

dimension():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

isStable():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

comparatorSubgraphIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startStablehloSortOptions(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addDimension(builder:flatbuffers.Builder, dimension:bigint) {
  builder.addFieldInt64(0, dimension, BigInt('0'));
}

static addIsStable(builder:flatbuffers.Builder, isStable:boolean) {
  builder.addFieldInt8(1, +isStable, +false);
}

static addComparatorSubgraphIndex(builder:flatbuffers.Builder, comparatorSubgraphIndex:number) {
  builder.addFieldInt32(2, comparatorSubgraphIndex, 0);
}

static endStablehloSortOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStablehloSortOptions(builder:flatbuffers.Builder, dimension:bigint, isStable:boolean, comparatorSubgraphIndex:number):flatbuffers.Offset {
  StablehloSortOptions.startStablehloSortOptions(builder);
  StablehloSortOptions.addDimension(builder, dimension);
  StablehloSortOptions.addIsStable(builder, isStable);
  StablehloSortOptions.addComparatorSubgraphIndex(builder, comparatorSubgraphIndex);
  return StablehloSortOptions.endStablehloSortOptions(builder);
}
}
