// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { StablehloComparisonDirection } from '../tflite/stablehlo-comparison-direction';
import { StablehloComparisonType } from '../tflite/stablehlo-comparison-type';


export class StablehloCompareOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StablehloCompareOptions {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStablehloCompareOptions(bb:flatbuffers.ByteBuffer, obj?:StablehloCompareOptions):StablehloCompareOptions {
  return (obj || new StablehloCompareOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStablehloCompareOptions(bb:flatbuffers.ByteBuffer, obj?:StablehloCompareOptions):StablehloCompareOptions {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StablehloCompareOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

comparisonDirection():StablehloComparisonDirection {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : StablehloComparisonDirection.STABLEHLO_COMPARISON_DIRECTION_EQ;
}

compareType():StablehloComparisonType {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : StablehloComparisonType.STABLEHLO_COMPARISON_TYPE_NOTYPE;
}

static startStablehloCompareOptions(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addComparisonDirection(builder:flatbuffers.Builder, comparisonDirection:StablehloComparisonDirection) {
  builder.addFieldInt32(0, comparisonDirection, StablehloComparisonDirection.STABLEHLO_COMPARISON_DIRECTION_EQ);
}

static addCompareType(builder:flatbuffers.Builder, compareType:StablehloComparisonType) {
  builder.addFieldInt32(1, compareType, StablehloComparisonType.STABLEHLO_COMPARISON_TYPE_NOTYPE);
}

static endStablehloCompareOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStablehloCompareOptions(builder:flatbuffers.Builder, comparisonDirection:StablehloComparisonDirection, compareType:StablehloComparisonType):flatbuffers.Offset {
  StablehloCompareOptions.startStablehloCompareOptions(builder);
  StablehloCompareOptions.addComparisonDirection(builder, comparisonDirection);
  StablehloCompareOptions.addCompareType(builder, compareType);
  return StablehloCompareOptions.endStablehloCompareOptions(builder);
}
}
