// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class UnsortedSegmentProdOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UnsortedSegmentProdOptions {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUnsortedSegmentProdOptions(bb:flatbuffers.ByteBuffer, obj?:UnsortedSegmentProdOptions):UnsortedSegmentProdOptions {
  return (obj || new UnsortedSegmentProdOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUnsortedSegmentProdOptions(bb:flatbuffers.ByteBuffer, obj?:UnsortedSegmentProdOptions):UnsortedSegmentProdOptions {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UnsortedSegmentProdOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startUnsortedSegmentProdOptions(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endUnsortedSegmentProdOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUnsortedSegmentProdOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  UnsortedSegmentProdOptions.startUnsortedSegmentProdOptions(builder);
  return UnsortedSegmentProdOptions.endUnsortedSegmentProdOptions(builder);
}
}
