// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class UnsortedSegmentMinOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UnsortedSegmentMinOptions {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUnsortedSegmentMinOptions(bb:flatbuffers.ByteBuffer, obj?:UnsortedSegmentMinOptions):UnsortedSegmentMinOptions {
  return (obj || new UnsortedSegmentMinOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUnsortedSegmentMinOptions(bb:flatbuffers.ByteBuffer, obj?:UnsortedSegmentMinOptions):UnsortedSegmentMinOptions {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UnsortedSegmentMinOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startUnsortedSegmentMinOptions(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endUnsortedSegmentMinOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUnsortedSegmentMinOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  UnsortedSegmentMinOptions.startUnsortedSegmentMinOptions(builder);
  return UnsortedSegmentMinOptions.endUnsortedSegmentMinOptions(builder);
}
}
