// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class UnsortedSegmentMaxOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UnsortedSegmentMaxOptions {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUnsortedSegmentMaxOptions(bb:flatbuffers.ByteBuffer, obj?:UnsortedSegmentMaxOptions):UnsortedSegmentMaxOptions {
  return (obj || new UnsortedSegmentMaxOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUnsortedSegmentMaxOptions(bb:flatbuffers.ByteBuffer, obj?:UnsortedSegmentMaxOptions):UnsortedSegmentMaxOptions {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UnsortedSegmentMaxOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startUnsortedSegmentMaxOptions(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endUnsortedSegmentMaxOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUnsortedSegmentMaxOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  UnsortedSegmentMaxOptions.startUnsortedSegmentMaxOptions(builder);
  return UnsortedSegmentMaxOptions.endUnsortedSegmentMaxOptions(builder);
}
}
