/**
 * C export formatting. Turns the emitted .tflite bytes into a C source array and
 * a ready TFLite Micro sketch with the op resolver and the arena size pre filled.
 * Pure string formatting, no Vue, no library, unit testable byte for byte. This
 * is what makes the train to microcontroller story real without touching the
 * library.
 */

/** A C friendly identifier derived from a project name. */
export function toCIdentifier(name: string): string {
  const cleaned = name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
  const base = cleaned.length ? cleaned : 'model';
  // A C identifier cannot start with a digit.
  return /^[0-9]/.test(base) ? `m_${base}` : base;
}

/**
 * Formats raw bytes as a C unsigned char array with a length constant. The array
 * is aligned to 16 bytes per row and marked with a 16 byte alignment attribute,
 * which TFLite Micro requires for the model buffer.
 *
 * @param bytes the .tflite file contents.
 * @param varName the C identifier for the array, for example "model".
 * @returns the C source as a single string.
 */
export function toCArray(bytes: Uint8Array, varName = 'model'): string {
  const id = toCIdentifier(varName);
  const rows: string[] = [];
  for (let i = 0; i < bytes.length; i += 16) {
    const slice = Array.from(bytes.subarray(i, i + 16)).map(
      (b) => `0x${b.toString(16).padStart(2, '0')}`,
    );
    rows.push(`  ${slice.join(', ')}${i + 16 < bytes.length ? ',' : ''}`);
  }
  return [
    `// Generated by VISE Studio. ${bytes.length} bytes.`,
    `#include <cstdint>`,
    ``,
    `alignas(16) const unsigned char ${id}_tflite[] = {`,
    rows.join('\n'),
    `};`,
    `const unsigned int ${id}_tflite_len = ${bytes.length};`,
    ``,
  ].join('\n');
}

/** The operators a generated sketch must register, derived from the model. */
export interface SketchOps {
  /** TFLM AddX resolver method names, for example "AddConv2D". */
  resolverCalls: string[];
}

/** Maps a tfjs layer class name to the TFLM resolver methods its ops need. */
const LAYER_RESOLVERS: Record<string, string[]> = {
  Conv2D: ['AddConv2D'],
  DepthwiseConv2D: ['AddDepthwiseConv2D'],
  Dense: ['AddFullyConnected'],
  MaxPooling2D: ['AddMaxPool2D'],
  AveragePooling2D: ['AddAveragePool2D'],
  GlobalAveragePooling2D: ['AddMean'],
  Flatten: ['AddReshape'],
  Reshape: ['AddReshape'],
  Softmax: ['AddSoftmax'],
  ReLU: ['AddRelu'],
  Add: ['AddAdd'],
};

/**
 * Derives the TFLM op resolver calls a model needs from its layer class names.
 * The int8 graph always carries a QUANTIZE and a DEQUANTIZE at the float
 * boundary, so those are always included. A Dense layer with a softmax activation
 * also needs SOFTMAX, since the converter lowers softmax to its own op.
 *
 * @param classNames the layer class names in model order.
 * @param hasSoftmaxHead true when the final layer fuses a softmax activation.
 * @returns the de duplicated resolver method names, boundary ops first.
 */
export function resolverCallsForLayers(classNames: string[], hasSoftmaxHead = false): string[] {
  const calls = new Set<string>(['AddQuantize', 'AddDequantize']);
  for (const name of classNames) {
    for (const call of LAYER_RESOLVERS[name] ?? []) calls.add(call);
  }
  if (hasSoftmaxHead) calls.add('AddSoftmax');
  return [...calls];
}

export interface SketchOptions {
  varName: string;
  /** Estimated tensor arena size in bytes. */
  arenaBytes: number;
  /** Input tensor shape, batch dimension included. */
  inputShape: number[];
  /** Number of output classes. */
  classCount: number;
  ops: SketchOps;
}

/**
 * Builds a minimal, compilable TFLite Micro sketch that loads the model array,
 * registers exactly the operators the model uses, allocates the estimated arena,
 * and runs one inference. The arena is rounded up and padded, since the estimate
 * is a floor, and the user is told to watch AllocateTensors for the real number.
 *
 * @returns the C++ sketch source as a single string.
 */
export function toTFLMSketch(options: SketchOptions): string {
  const id = toCIdentifier(options.varName);
  const resolverCount = options.ops.resolverCalls.length;
  // Pad the estimate by a quarter and round to a kilobyte. The estimate is a
  // floor; the interpreter reports the exact figure at AllocateTensors.
  const padded = Math.ceil((options.arenaBytes * 1.25) / 1024) * 1024;
  const adds = options.ops.resolverCalls.map((call) => `  resolver.${call}();`).join('\n');
  const inputComment = options.inputShape.join(' x ');

  return [
    `// Generated by VISE Studio. TFLite Micro sketch for ${id}.`,
    `// Model input ${inputComment}, ${options.classCount} output classes.`,
    `// The arena below is an estimate padded by 25 percent. Check the value`,
    `// AllocateTensors reports and tighten it for production.`,
    ``,
    `#include "tensorflow/lite/micro/micro_interpreter.h"`,
    `#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"`,
    `#include "tensorflow/lite/schema/schema_generated.h"`,
    `#include "${id}_model.h" // declares ${id}_tflite`,
    ``,
    `namespace {`,
    `constexpr int kArenaSize = ${padded};`,
    `alignas(16) uint8_t tensor_arena[kArenaSize];`,
    `} // namespace`,
    ``,
    `void setup() {`,
    `  const tflite::Model* model = tflite::GetModel(${id}_tflite);`,
    ``,
    `  static tflite::MicroMutableOpResolver<${resolverCount}> resolver;`,
    adds,
    ``,
    `  static tflite::MicroInterpreter interpreter(`,
    `      model, resolver, tensor_arena, kArenaSize);`,
    `  interpreter.AllocateTensors();`,
    ``,
    `  TfLiteTensor* input = interpreter.input(0);`,
    `  // Copy your ${inputComment} float input into input->data.f, then:`,
    `  interpreter.Invoke();`,
    `  TfLiteTensor* output = interpreter.output(0);`,
    `  // output->data.f holds ${options.classCount} class scores.`,
    `}`,
    ``,
    `void loop() {}`,
    ``,
  ].join('\n');
}
